### PR TITLE
update settings form for D11 compatibility

### PR DESCRIPTION
**Pull request by jackrabbithanna**
Overview
----------------------------------------
Necessary update for Drupal 11. Looks to be backward compatible for Drupal 10.

Before
----------------------------------------
Error going to CiviCRM Entity settings page

 Uncaught PHP Exception ArgumentCountError: "Too few arguments to function Drupal\Core\Form\ConfigFormBase::__construct(), 1 passed in /var/www/web/drupal-11/web/modules/contrib/civicrm_entity/src/Form/CivicrmEntitySettings.php on line 84 and exactly 2 expected" at /var/www/web/drupal-11/web/core/lib/Drupal/Core/Form/ConfigFormBase.php line 41

After
----------------------------------------
No error

### CODE REVIEW

**Comment by jackrabbithanna** [comment]
I verified changes work in 10.1, 10.2, 10.3-beta1 and 11
